version: '3.8'

services:
  app:
    build: .
    container_name: act-audit-summary
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
